- name: variables
  hosts: localhost
  vars: # declaring variables
    Course: "Ansible"
    Trainer: "SivaKumar"
    Duration: "120hrs"
  tasks: 
  - name: printing variables
    ansible.builtin.debug:
      msg: "Hi, I'm learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."
  - name: print override information
    vars: #Task level variables 
      Course: "Docker"
    ansible.builtin.debug:
      msg: "Hi, I'm learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."