- name : data types
  hosts : localhost
  vars :
    Course: devops with AWS #string
    Tools: #list
    - Linux
    - Shell
    - Ansible
    Experince: #map
      Devops: 3
      AWS: 2
      Docker: 1
    Realtimeproject: True
  tasks:
    ansible.builtin.debug:
      msg "Course: {{Course}}, Tools covered: {{Tools}}, Experience is: {{Experience}}, is real project: {{RealProject}}"