- name: default value
  hosts: localhost
  tasks: 
  - name: print default value
    ansible.builtin.debug:
      msg: "hello {{ course | default('ansible') }}"
  
- name: upper case
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning"
  tasks: 
  - name: convert into upper case
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

- name: lower case
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning"
  tasks: 
  - name: convert into lower case
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1, 2, 3, 3, 4, 4, 5]
  tasks: 
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

- name: print min and max
  hosts: localhost
  vars:
    ages: [18, 21, 25, 29, 33]
  tasks: 
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "min age: {{ ages | min }}, max age: {{ ages | max }}"

- name: convert dict into item/list
  hosts: localhost
  vars:
    my_dict: 
      course: DevOps
      trainer: Siva
      duration: 120_Days
  tasks: 
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_dict }}"
  - name: after convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_dict | dict2items }}"

- name: convert dict into item/list
  hosts: localhost
  vars:
    my_list: 
      -     - {'key': 'Course', 'value': 'Ansible'}
    - {'key': 'Trainer', 'value': 'Sivakumar'}
    - {'key': 'Duration', 'value': '120_Days'}
  tasks: 
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_list }}"
  - name: after convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_list | items2dict }}"

