- name: command vs shell
  hosts: localhost
  tasks:
  - name: command module
    ansible.builtin.command: "echo 'Hi, this is from command module' > /tmp/command.txt "

  - name: shell module
    ansible.builtin.shell: "echo 'Hi, this is from shell module' > /tmp/shell.txt "

    # simple commands without the need of shell variables, environments and features like redirection, pipes, & go for command module.
    # If we need to run complex commands or scripts go for shell module.
    # Whatever works in command module, it will work in shell module, but vice versa is not true.